services:
  postgres:
    image: postgres:16-alpine
    container_name: quotes_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quotes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quotes"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata: